export const BUSINESS_ITEMS = [
  {
    id: 1,
    title: "기업자문",
    titleEn: "Corporate Consulting",
    description: "인사노무 리스크 예방 및 자문 제공",
    image: "/business/기업자문.jpg",
    slug: "기업자문",
  },
  {
    id: 2,
    title: "노동사건",
    titleEn: "Labor Disputes",
    description: "노동사건 대응 및 자문 제공",
    image: "/business/노동사건.jpg",
    slug: "노동사건",
  },
  {
    id: 3,
    title: "컨설팅",
    titleEn: "HR Consulting",
    description: "인사노무관리 체계화 컨설팅",
    image: "/business/컨설팅.png",
    slug: "컨설팅",
  },
  {
    id: 4,
    title: "노동조합",
    titleEn: "Labor Union",
    description: "노동조합 대응 및 단체교섭 지원",
    image: "/business/노동조합.jpg",
    slug: "노동조합",
  },
  {
    id: 5,
    title: "기업강의",
    titleEn: "Corporate Lecture",
    description: "맞춤형 노동관계법 기업 교육",
    image: "/business/기업강의.jpg",
    slug: "기업강의",
  },
  {
    id: 6,
    title: "산업재해/어선원재해",
    titleEn: "Industrial Accident",
    description: "산재 인정 및 보상 청구 지원",
    image: "/business/산업재해.png",
    slug: "산업재해",
  },
  {
    id: 7,
    title: "급여 아웃소싱/4대보험",
    titleEn: "Payroll Outsourcing",
    description: "급여 및 4대보험 전문 관리",
    image: "/business/급여.jpg",
    slug: "급여",
  },
] as const
